// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryReading struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ElementId      string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	ElementType    string                 `protobuf:"bytes,2,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LatencyMs      float64                `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ThroughputMbps float64                `protobuf:"fixed64,5,opt,name=throughput_mbps,json=throughputMbps,proto3" json:"throughput_mbps,omitempty"`
	PacketLossPct  float64                `protobuf:"fixed64,6,opt,name=packet_loss_pct,json=packetLossPct,proto3" json:"packet_loss_pct,omitempty"`
	CpuUsagePct    float64                `protobuf:"fixed64,7,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	MemoryUsagePct float64                `protobuf:"fixed64,8,opt,name=memory_usage_pct,json=memoryUsagePct,proto3" json:"memory_usage_pct,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryReading) Reset() {
	*x = TelemetryReading{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryReading) ProtoMessage() {}

func (x *TelemetryReading) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryReading.ProtoReflect.Descriptor instead.
func (*TelemetryReading) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryReading) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *TelemetryReading) GetElementType() string {
	if x != nil {
		return x.ElementType
	}
	return ""
}

func (x *TelemetryReading) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryReading) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TelemetryReading) GetThroughputMbps() float64 {
	if x != nil {
		return x.ThroughputMbps
	}
	return 0
}

func (x *TelemetryReading) GetPacketLossPct() float64 {
	if x != nil {
		return x.PacketLossPct
	}
	return 0
}

func (x *TelemetryReading) GetCpuUsagePct() float64 {
	if x != nil {
		return x.CpuUsagePct
	}
	return 0
}

func (x *TelemetryReading) GetMemoryUsagePct() float64 {
	if x != nil {
		return x.MemoryUsagePct
	}
	return 0
}

type TelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stored        bool                   `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryAck) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *TelemetryAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\x10TelemetryReading\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12!\n" +
	"\felement_type\x18\x02 \x01(\tR\velementType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\x12'\n" +
	"\x0fthroughput_mbps\x18\x05 \x01(\x01R\x0ethroughputMbps\x12&\n" +
	"\x0fpacket_loss_pct\x18\x06 \x01(\x01R\rpacketLossPct\x12\"\n" +
	"\rcpu_usage_pct\x18\a \x01(\x01R\vcpuUsagePct\x12(\n" +
	"\x10memory_usage_pct\x18\b \x01(\x01R\x0ememoryUsagePct\"@\n" +
	"\fTelemetryAck\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2Y\n" +
	"\x10TelemetryService\x12E\n" +
	"\rSendTelemetry\x12\x1b.telemetry.TelemetryReading\x1a\x17.telemetry.TelemetryAckB\x10Z\x0enetpulse/protob\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_proto_goTypes = []any{
	(*TelemetryReading)(nil),      // 0: telemetry.TelemetryReading
	(*TelemetryAck)(nil),          // 1: telemetry.TelemetryAck
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_telemetry_proto_depIdxs = []int32{
	2, // 0: telemetry.TelemetryReading.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: telemetry.TelemetryService.SendTelemetry:input_type -> telemetry.TelemetryReading
	1, // 2: telemetry.TelemetryService.SendTelemetry:output_type -> telemetry.TelemetryAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
